### ISSUE TITLE
스트릭 api수정 요망

### ISSUE THREAD

**Issue by donghyun1998** [mejaiGG/Backend#5]
메자이 스택 기능 추가로

스트릭 api 아래처럼 수정 부탁드립니다옹
{
	{date: '2021-10-10', gameCount: 3, imgName : 'mejai3.png'}, 
 	{date: '2021-10-11', gameCount: 2, imgName : 'mejai2.png'}, 
	{date: '2021-10-12', gameCount: 1, imgName : 'mejai1.png'}
}
이렇게 3번째 인자로 해당 gameCount에 해당하는 이미지 링크를 넣어주세옹
각 메자이 이미지 캐톡으로 보내겠습니다옹

**Comment by Hawardshin** [comment]
확인임다 다음 풀리퀘때 수정할께요

**Comment by Hawardshin** [comment]
요거 dto imgUrl로 할께요~

**Comment by donghyun1998** [comment]
확인입니다 내일 작업해서 올릴게요~!
